name: Update AREDL Rankings

on:
  schedule:
    - cron: "0 */6 * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Fetch AREDL Levels
        run: |
          curl -L -o aredl-ranks.json https://api.aredl.net/v2/api/aredl/levels

      - name: Fetch AREDL User
        run: |
          curl -L -o aredl-user.json https://api.aredl.net/v2/api/aredl/profile/1163166644546322533
      - name: Fetch AREDL Clan
        run: |
          curl -L -o aredl-clan.json https://api.aredl.net/v2/api/aredl/clan/a35a4749-fce4-43e2-8985-d03691c4a07f

      - name: Commit changes
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"

          git add aredl-ranks.json aredl-user.json aredl-clan.json

          git diff --staged --quiet || git commit -m "Update AREDL data"

          git push